Canonicalize `cwd` in `CommandHelper::new()`
`workspace_root` is [canonicalized](https://github.com/martinvonz/jj/blob/41a2855b4fd84d8811d295dcaa0ea0aa0d5be171/lib/src/workspace.rs#L119), but `cwd` [isn't](https://github.com/martinvonz/jj/blob/41a2855b4fd84d8811d295dcaa0ea0aa0d5be171/src/cli_util.rs#L581). When [working with relative paths](https://github.com/martinvonz/jj/blob/41a2855b4fd84d8811d295dcaa0ea0aa0d5be171/src/cli_util.rs#L749-L760), this leads to issues in Windows: canonicalized paths start with `\\?\`, whereas non-canonicalized paths do not. Therefore, paths were formatted canonicalized, and commands did not accept non-canonicalized paths:

```
$ jj st
Parent commit: bdb62c9 canonicalize cwd in cli_util.rs
Working copy : 059c104379cd (no description set)
Working copy changes:
A \\?\C:\github.com\71\jj\.vscode\launch.json

$ jj diff .vscode\launch.json
Error: Path ".vscode\launch.json" is not in the repo

$ jj diff \\?\C:\github.com\71\jj\.vscode\launch.json
Added regular file \\?\C:\github.com\71\jj\.vscode\launch.json:
...
```

With this change:
```
$ jj st
Parent commit: bdb62c9 canonicalize cwd in cli_util.rs
Working copy : 059c104379cd (no description set)
Working copy changes:
A .vscode\launch.json

$ jj diff .vscode\launch.json
Added regular file .vscode\launch.json:
...
```